repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: dprint
        name: dprint
        entry: dprint fmt --incremental=false --allow-no-files
        language: node
        pass_filenames: false
        additional_dependencies: ["dprint"]
      - id: ruff_format
        name: Ruff format
        stages: [commit]
        language: system
        entry: uv run ruff format
        types: [python]
      - id: ruff_lint
        name: Ruff lint
        stages: [commit]
        language: system
        entry: uv run ruff check
        types: [python]
      - id: pydocstringformatter
        name: pydocstringformatter
        stages: [commit]
        language: system
        entry: uv run pydocstringformatter src tests
        types: [python]
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: uv run mypy
        types: [python]
        require_serial: true
      - id: pydoclint
        name: pydoclint
        stages: [commit]
        language: system
        entry: uv run pydoclint src
        types: [python]
        require_serial: true
      - id: update-conda
        name: Update Conda environments
        stages:
          - commit
        language: system
        entry: "mise run conda:export"
        require_serial: true
        pass_filenames: false
