name: spyder
channels:
- conda-forge
- nodefaults
dependencies:
- spyder-kernels >=2.5.2,<3
- spyder >=5.5.1,<6
- ruff >=0.6.8,<0.7
- pre-commit >=3.8.0,<4
- pre-commit-hooks >=4.6.0,<5
- pytest >=8.3.3,<9
- python >=3.12
- pip
- pip:
  - pydoclint>=0.5.9, <0.6
  - pydocstringformatter>=0.7.3, <0.8
  - ruff
  - pytest
  - pre-commit
  - pre-commit-hooks
  - -e .
  - matplotlib>=3.9.2
  - numpy>=2.1.1
  - returns>=0.23.0, <0.24
  - rich>=13.7.1
