[tool.poetry]
name = "plan-a-trip-to-mars"
version = "0.1.1"
description = ""
authors = ["engeir <eirroleng@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
plan-a-trip-to-mars = "plan_a_trip_to_mars.__main__:main"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
matplotlib = "^3.4.3"
numpy = "^1.21.2"
importlib-metadata = "^4.12.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
isort = "^5.9.3"
pre-commit = "^2.14.0"
pre-commit-hooks = "^4.0.1"
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
